#!/usr/bin/env python
# dc-server

import SimpleXMLRPCServer, sys, os, threading
import DcServer
workpath = '/root/deskcloud-server/'
rpcport = 8772

def server_thread():
    host = '0.0.0.0'
    obj = DcServer.DcServer()
    server = SimpleXMLRPCServer.SimpleXMLRPCServer((host, rpcport), logRequests=False)
    server.register_instance(obj)
    server.serve_forever()

def main():
    thr = threading.Thread(target=server_thread)
    thr.start()

if __name__ == "__main__":
    try:
        pid = os.fork()
        if pid > 0:
            sys.exit(0)
    except OSError, e:
        print >>sys.stderr, "fork #1 failed: %d (%s)" % (e.errno, e.strerror)
        sys.exit(1)
    os.chdir(workpath)
    os.setsid()
    os.umask(0)
    try:
        pid = os.fork()
        if pid > 0:
            print "Daemon PID %d" % pid
            sys.exit(0)
    except OSError, e:
        print >>sys.stderr, "fork #2 failed: %d (%s)" % (e.errno, e.strerror)
        sys.exit(1)
    main()
